# Generated by Django 6.0 on 2026-01-11 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=30, unique=True)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('sexo', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('celular', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('departamento', models.CharField(blank=True, default='', max_length=80)),
                ('provincia', models.CharField(blank=True, default='', max_length=80)),
                ('distrito', models.CharField(blank=True, default='', max_length=80)),
                ('programa_id', models.CharField(blank=True, default='', max_length=64)),
                ('ciclo_actual', models.IntegerField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, default='', max_length=30)),
                ('seccion', models.CharField(blank=True, default='', max_length=30)),
                ('periodo_ingreso', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(blank=True, default='activo', max_length=30)),
                ('apoderado_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('apoderado_dni', models.CharField(blank=True, default='', max_length=12)),
                ('apoderado_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
