# Generated by Django 5.2.10 on 2026-01-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ciclo_actual',
            new_name='ciclo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='periodo_ingreso',
            new_name='codigo_modular',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fecha_nacimiento',
            new_name='fecha_nac',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='departamento',
            new_name='lengua',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='direccion',
            new_name='nombre_institucion',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dni',
            new_name='num_documento',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apoderado_dni',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apoderado_nombre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apoderado_telefono',
        ),
        migrations.RemoveField(
            model_name='student',
            name='codigo_estudiante',
        ),
        migrations.RemoveField(
            model_name='student',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programa_id',
        ),
        migrations.AddField(
            model_name='student',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='discapacidad',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gestion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='periodo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='programa_carrera',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
