# Generated by Django 5.2.10 on 2026-01-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0002_rename_ciclo_actual_student_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.plan'),
        ),
    ]
