# Generated by Django 6.0 on 2026-01-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACADEMIC_ACTA', 'ACADEMIC_ACTA'), ('ADMISSION_ACTA', 'ADMISSION_ACTA'), ('GRADE_SLIP', 'GRADE_SLIP'), ('ENROLLMENT_CONST', 'ENROLLMENT_CONST'), ('KARDEX', 'KARDEX'), ('CERTIFICATE', 'CERTIFICATE')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='PENDING', max_length=12)),
                ('file_path', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
