# Generated by Django 6.0 on 2026-01-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('IN_APP', 'IN_APP')], max_length=10)),
                ('to', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rendered', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='QUEUED', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('channel', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('IN_APP', 'IN_APP')], max_length=10)),
                ('email_subject', models.CharField(blank=True, default='', max_length=200)),
                ('email_html', models.TextField(blank=True, default='')),
                ('sms_text', models.CharField(blank=True, default='', max_length=300)),
                ('in_app_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('IN_APP', 'IN_APP')], max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='notifications.notificationtemplate')),
            ],
            options={
                'unique_together': {('event_key', 'channel')},
            },
        ),
    ]
