# Generated by Django 5.2.10 on 2026-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_institutionsettings'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='catalog_teachers', to='academic.course'),
        ),
    ]
