# Generated by Django 5.2.10 on 2026-01-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='admission.application')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admission.career')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'unique_together': {('application', 'career')},
            },
        ),
    ]
