# Generated by Django 6.0 on 2026-01-11 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True)),
                ('processing_days', models.PositiveIntegerField(default=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('applicant_name', models.CharField(max_length=160)),
                ('applicant_document', models.CharField(blank=True, max_length=40, null=True)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='RECEIVED', max_length=16)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_assigned', to=settings.AUTH_USER_MODEL)),
                ('current_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa_partes.office')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesa_partes.proceduretype')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mesa_partes.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='procedures/')),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('doc_type', models.CharField(blank=True, max_length=60)),
                ('size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mesa_partes.procedure')),
            ],
        ),
    ]
