# Generated by Django 6.0 on 2026-01-11 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['timestamp', 'action'], name='audit_logs_timesta_05ea8c_idx'), models.Index(fields=['entity', 'entity_id'], name='audit_logs_entity_22e216_idx')],
            },
        ),
    ]
